SELECT PRODUCT.PRODUCT_CODE, SUM(SALES_AMOUNT * PRODUCT.PRICE) AS SALES
FROM PRODUCT LEFT JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;