# SELECT COUNT(FISH_NAME) AS FISH_COUNT, FISH_NAME FROM FISH_NAME_INFO
# LEFT JOIN FISH_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
# GROUP BY FISH_NAME
# ORDER BY FISH_COUNT DESC

SELECT  COUNT(FI.ID) AS FISH_COUNT
        ,FN.FISH_NAME
  FROM  FISH_INFO AS FI
  JOIN  FISH_NAME_INFO AS FN
    ON  FI.FISH_TYPE = FN.FISH_TYPE
 GROUP
    BY  FISH_NAME
 ORDER
    BY  FISH_COUNT DESC
;